"""empty message

Revision ID: 333c2776447b
Revises: 0ac72a8c1322
Create Date: 2020-03-10 19:41:40.168361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333c2776447b'
down_revision = '0ac72a8c1322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=240), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('detector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detector_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('detector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'detector_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detector_user')
    op.drop_table('alerts')
    op.drop_table('users')
    # ### end Alembic commands ###
